macro(_cmrk_bail MESSAGE)
  if (ARG_REQUIRED)
    message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION}: ${MESSAGE}")
  else ()
    message(VERBOSE "${CMAKE_CURRENT_FUNCTION}: ${MESSAGE}")
    set("${ARG_OUTPUT_VARIABLE}" "${output_value}")
    return()
  endif ()
endmacro()
