macro(_cmrk_bail reason)
  if (ARG_REQUIRED)
    message(FATAL_ERROR "${reason}")
  else ()
    message(VERBOSE "${reason}")
    set("${ARG_OUTPUT_VARIABLE}" "${output_value}" PARENT_SCOPE)
    return()
  endif ()
endmacro()
